language: node_js
node_js:
- '0.10'
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_script:
- npm install -g grunt-cli
env:
  matrix:
  - CXX=g++-4.8
  global:
    secure: aOSQkEeIGiLNcMucvVJF4mBpukVkDM0+UbiuX1dunk8tPQbfKlNEACyEZneMAYCDTJBT2wlujKVEIKMzaBsrUKRKPYZ5vi77X/DrowW+3pGF0r2AdYxJKNO3FEHxzCSYaVxusDtMT0ohsDBLwyPxjll8zu9PPfcUe6EIb+AWemQ=
deploy:
  provider: npm
  email: jononor@gmail.com
  skip_cleanup: true
  api_key:
    secure: FjHI+CEzM1CqgynAdIZtd1XPpDEUOplHWOpKRa4epZxm6UK5x5uU1qN8BjntaRdpQyMHF8uhpf8VufWZFPiErymEz/kKa7IURQyL2rESaA39oB/xkXiNAxrxdIYgyM+vE3IgFXY1kaSYXqTXqdUHyb7mG9a2P8lwtSeAtQC0vzk=
  on:
    tags: true
    repo: the-grid/apidocs
after_deploy:
- grunt gh-pages
