language: node_js
node_js:
- '4.6'
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
before_script:
- npm install -g grunt-cli
env:
  matrix:
  - CXX=g++-4.8
  global:
    secure: aOSQkEeIGiLNcMucvVJF4mBpukVkDM0+UbiuX1dunk8tPQbfKlNEACyEZneMAYCDTJBT2wlujKVEIKMzaBsrUKRKPYZ5vi77X/DrowW+3pGF0r2AdYxJKNO3FEHxzCSYaVxusDtMT0ohsDBLwyPxjll8zu9PPfcUe6EIb+AWemQ=
deploy:
  provider: npm
  email: henri.bergius@iki.fi
  skip_cleanup: true
  api_key:
    secure: YIvAJl+dEyCg6d6nY0Zm2ZeRnS3PuK2zXFwhqU0RBuAeG6DpEpu/0bIMWov4TqkQ6AzYHEnxSivcCEkQCMKTXr1RrsqH58kzIRR1BFRsqdrZLGIHqiBOtPuHu0WemoaMYtvKW/u8Mdn1y9pRvtBOkct+wqBomW6CYHJ6rokAPPc=
  on:
    tags: true
    repo: the-grid/apidocs
after_deploy:
- grunt gh-pages
