---
id: base.json
"$schema": "http://json-schema.org/draft-04/schema"
title: Base definitions for Grid content types
definitions:
  uuid:
    description: Unique identifier
    format: uuid
    pattern: "^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$"
    example: 01234567-89ab-cdef-0123-456789abcdef
    type: string
  url:
    description: Unique Resource Locator
    format: url
    example: http://example.net/foo
    type: string
  hexcolor:
    description: "#RGB color"
    format: rgbhexcolor
    pattern: "^#([a-fA-F0-9]{6}|[a-fA-F0-9]{3})$"
    example: "#aa33cc"
    type: string
  sites:
    type: array
    description: Collection of websites associated with the resource
    items:
      type: string
    uniqueItems: true
    example:
    - "the-domains/the-grid"
  geo:
    type: object
    description: Geographical data
    properties:
      latitude:
        name: latitude
        type: number
        description: Latitude coordinate
        example: 45.5
      longitude:
        name: longitude
        type: number
        description: Longitude coordinate
        example: -122.7
      zoom:
        name: zoom
        type: number
        description: Zoom level of map
        example: 4.0

