---
id: "siteconfig.json"
"$schema": "http://json-schema.org/draft-04/schema"
title: Site config
description: Configuration of a single site
type: object
properties:
  name:
    type: string
    description: Website name
  style:
    type: string
    description: Layout filter selected for the site
    example: taylor
    default: taylor
  favicon:
    type: string
    description: Favicon URL
  logo:
    type: string
    description: SVG logo URL
  cta:
    type: object
    required:
    - version
    properties:
      domain:
        name: domain
        description: CDN to serve the CtA from
        type: string
      bucket:
        name: bucket
        description: S3 bucket to serve the CtA from
        type: string
      version:
        name: version
        description: CtA version to use on site
        type: string
        example: '1.0.0'
  analytics:
    type: object
    properties:
      google:
        name: google
        type: string
        description: Google Analytics ID for the site
      facebook:
        name: facebook
        type: string
        description: Facebook tracking ID for the site
      twitter:
        name: twitter
        type: string
        description: Twitter tracking ID for the site
  image_filters:
    type: object
    properties:
       server:
         type: string
         description: 'URL to the imgflo.org server'
       key:
         type: string
         description: 'imgflo API key'
       secret:
         type: string
         description: 'imgflo API secret'
       required: ['server', 'key', 'secret']
  opengraph:
    type: object
    required:
    - type
    - image
    properties:
      image:
        name: image
        description: Default image to use when sharing the website
        type: string
      type:
        name: type
        description: Type of the website
        type: string
      appId:
        name: appId
        type: string
        description: Facebook App ID associated with the site
  collections:
    type: array
    minItems: 1
    uniqueItems: true
    items:
      "$ref": "collection.json"
  color:
    type: object
    properties:
      brandColors:
        type: array
        default: []
        items:
          "$ref": "base.json#/definitions/hexcolor"
        description: "The user-selected brand colors for the site"
      brandStrength:
        type: number
        default: 0.0
        minimum: 0.0
        maximum: 1.0
        description: "How strongly to tend towards brandColors, as opposed to content colors (adaptive)"
      lightness:
        type: number
        default: 0.5
        minimum: 0.0
        maximum: 1.0
      saturation:
        type: number
        default: 0.5
        minimum: 0.0
        maximum: 1.0
  layout_spectrum:
    type: number
    description: ""
    default: 0.5
    minimum: 0.0
    maximum: 1.0
  typography_spectrum:
    type: number
    description: ""
    default: 0.5
    minimum: 0.0
    maximum: 1.0
  site_lang:
    type: string
    description: Primary site content langauge; ISO 693-1 format
    example: ar
    default: en
  author:
    type: object
    properties:
      name:
        type: string
      email:
        type: string
      url:
        type: string
  navigation:
    type: array
    description: "External links to include in site navigation"
    default: []
    items:
      type: object
      properties:
        name:
          description: "Name to show"
          type: string
        url:
          description: "URL to link to"
          type: string
        rel:
          description: "HTML link relation"
          type: string
  profiles:
    type: array
    description: "Social media profile links associated with the site"
    default: []
    items:
      type: object
      properties:
        name:
          type: string
        url:
          type: string
  auto_approve:
    description: Whether to publish site changes without design review
    type: boolean

required: [name]
