# Examples of site configs
-
  _valid: true
  _name: 'minimal'
  _data:
    name: The Grid
-
  _valid: true
  _name: 'thegrid.io-launchsite'
  _data:
    name: The Grid
    favicon: "https://passport.thegrid.io/favicon.ico"
    style: A1
    site_lang: en
    cta:
      domain: //s3-us-west-2.amazonaws.com
      bucket: /cdn.thegrid.io
      version: 0.2.5
    analytics:
      google: UA-50607580-1
      facebook: "295556487279234"
      twitter: l4y05
    opengraph:
      appId: "1517733501804443"
      image: "http://s3-us-west-2.amazonaws.com/cdn.thegrid.io/assets/images/purus-fb.png"
      type: website
    collections:
      - filter:
          notTag:
            tag: ancillary
        index:
          path: /
          number: 50
      - filter:
          tag:
            tag: ancillary
        permalink:
          path: "/:title/"
      - filter:
          tag:
            tag: team
        permalink:
          path: /team/
-
  _valid: false
  _name: 'number-as-name'
  _data:
    name: 123
-
  _valid: true
  _name: 'strong-brand-colors'
  _data:
    name: 'GSS site'
    color:
        brandColors: [ "#FFFC4F", "#3AFFD6" ]
        brandStrength: 0.9
-
  _valid: true
  _name: 'typography-layout-spectrums'
  _data:
    name: 'GSS site'
    typography: 0.9
    layout: 0.1
-
  _valid: false
  _name: 'invalid-brand-color'
  _data:
    name: 'GSS site'
    color:
        brandColors: [ "#ÆÆÆC44" ]
-
  _valid: true
  _name: 'with-image-filters'
  _data:
    name: 'imgflo using site'
    image_filters:
      server: "https://imgflo.herokuapp.com/"
      key: "vahj1001exotieMo"
      secret: "queeLegh6phu4yei"
-
  _valid: false
  _name: 'undefined site_lang'
  _data:
    name: The Grid
    site_lang: [1, 2, 3]
